export { default as logo } from "./logo.png";
export { default as logoicon } from "./logoicon.png";
export { default as hero } from "./hero.png";
export { default as leftelip } from "./t-l-ellipse.png";
export { default as rightelip } from "./t-r-ellipse.png";
export { default as bottomrightelip } from "./b-r-ellipse.png";
export { default as votebanner } from "./votebanner.png";
export { default as space } from "./Scene_BlueGreenGold_NoLimits.png";
export { default as landingBg } from "./landing-bg.png";
